
---
spring:
  profiles:
    active: local
#  main:
#    banner-mode: 'off'
  jmx:
    enabled: true
  banner:
    location: classpath:/banner.txt

  jackson:
    serialization:
      INDENT_OUTPUT: false

  mail:
    host: localhost
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: flase

  cache:
    jcache:
      config: 'classpath:ehcache3.xml'


debug:
  mode: true

api:
  domain: localhost
  page-size: 5


# monitor : default path /actuator/health , then dependency : 'org.springframework.boot:spring-boot-starter-actuator'
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /monitor


# spring cloud aws configure. https://cloud.spring.io/spring-cloud-aws/reference/html/
cloud:
  aws:
    credentials:
      useDefaultAwsCredentialsChain: true
    region:
      static: ap-northeast-1
    stack:
      auto: false

#aws:
#  paramstore:
#    prefix: /config
#noah:
#  e1: ${my_db_datasource_json}
#  e2: "#{ new com.fasterxml.jackson.databind.ObjectMapper().readTree( '${my_db_datasource_json}' ).get('username').asText() }"

---
spring:
  profiles: local

  jackson:
    serialization:
      INDENT_OUTPUT: false

  h2:
    console:
      enabled: true
      path: /h2-admin


debug:
  mode: true

books:
  datasource:
#    jdbc-url: jdbc:mysql://localhost:3306/books?useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:h2:mem:test;INIT=runscript from 'classpath:/example-books.sql'
    driverClassName: org.h2.Driver
    username: root
    password: 123456
    maximum-pool-size: 1
    properties:
      hibernate:
        show-sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        ddl-auto: false
#    jpa:
#      database-platform: org.hibernate.dialect.MySQLDialect


logs:
  datasource:
    #    jdbc-url: jdbc:mysql://localhost:3306/books?useUnicode=true&characterEncoding=utf-8
    #    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:h2:mem:test;INIT=runscript from 'classpath:/example-logs.sql'
    driverClassName: org.h2.Driver
    username: root
    password: 123456
    maximum-pool-size: 1
    properties:
      hibernate:
        show-sql: true
        #        dialect: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        ddl-auto: false

---
spring:
  profiles: dev
  # tomcat mode
  jmx:
    enabled: false

  jackson:
    serialization:
      INDENT_OUTPUT: false

debug_mode: true


books:
  datasource:
    jndi-name: jdbc/my-jndi
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        format_sql: false
        ddl-auto: false

---
spring:
  profiles: production


debug_mode: false
